setenv('CUDA_VISIBLE_DEVICES','0,1')
if isempty(gcp('nocreate'))
    parpool('local',8);
end
checkpointpath = "C:\project_data\fastrcnn_walls\training_checkpoints";
load('latest_settings.mat')
load('C:\project_data\fastrcnn_walls\training_checkpoints\faster_rcnn_stage_1_checkpoint__3750__2020_10_23__17_25_50.mat')
[detector,info] = trainFasterRCNNObjectDetector(training_data,detector,options,...
    'TrainingMethod','four-step',...
    'FreezeBatchNormalization',0,...
    'NumStrongestRegions',2000,...
    'NumRegionsToSample',[128 128 128 128]);