setenv('CUDA_VISIBLE_DEVICES','1,2')
if isempty(gcp('nocreate'))
    parpool('local',8);
end
load('listofimages.mat')
checkpointpath = "C:\project_data\fastrcnn_walls\training_checkpoints";
no_samples = 500;
load('detector_1200.mat')

image_list = image_list(randperm(length(image_list)),:);
training_data = cell(no_samples,10);
for i = 1:no_samples
    progressbar(i/no_samples)
    training_data{i,1} = image_list{i,1};
    temp = loadannotsfromfile(image_list{i,2});
    for j = 1:size(temp,1)
        training_data{i,temp(j,1)+1} = [training_data{i,temp(j,1)+1};temp(j,2:5)];
    end
end
training_data = cell2table(training_data);
training_data.Properties.VariableNames = {'images' 'wall' 'floor' 'ceiling' 'bed' 'couch' 'chair' 'table' 'drawer' 'door'}; 
options = trainingOptions('adam',...
    'GradientDecayFactor',0.9,          'SquaredGradientDecayFactor',0.999,...
    'Epsilon',1e-8,                     'InitialLearnRate',0.0001,...
    'LearnRateSchedule','piecewise',    'LearnRateDropPeriod',5,...
    'LearnRateDropFactor',0.1,          'L2Regularization',0.0001,...
    'GradientThresholdMethod','l2norm', 'GradientThreshold',Inf,...
    'MaxEpochs',15,                     'MiniBatchSize',4,...
    'Verbose',true,                     'VerboseFrequency',25,...
    'ValidationFrequency',50,           'Shuffle','once',...
    'CheckpointPath',checkpointpath,    'ExecutionEnvironment','multi-gpu',...
    'DispatchInBackground',1,           'WorkerLoad',[1 1 0 0 0 0 0 0]);
save('latest_settings.mat','training_data','options')

[detector,info] = trainFasterRCNNObjectDetector(training_data,detector,options,...
    'TrainingMethod','four-step',...
    'FreezeBatchNormalization',0,...
    'NumStrongestRegions',2000,...
    'NumRegionsToSample',[128 128 128 128]);

